[package]
name = "editor-angular"
version = "0.1.0"
description = "Editor ultraligero para Angular"
authors = ["Dewinson Cruz"]
edition = "2021"

[lib]
# The `_lib` suffix is necessary on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "editor_angular_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
ignore = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify-debouncer-mini = "0.7.0"
trash = "5.2.9"
dunce = "1.0.5"
portable-pty = "0.9.0"
tokio = { version = "1.53.2", features = ["net", "sync", "macros", "time"] }
tokio-tungstenite = "0.30.0"
futures-util = "0.3.34"
uuid = { version = "1.27.0", features = ["v4"] }

# https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
